language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

# install dependencies
install: 
  -pip install -r requirements.txt

# install dependencies
install:
  - pip install codecov

# run scripts
#script:
#  - coverage erase
#  - coverage run test_webapp.py && coverage html

after_success:
  - codecov

